### PR TITLE
Added the dew point function and some more trivial pressure conversions.

### PR DESCRIPTION
**Pull request by Pavel-Sayekat**
Added the dew point function and some more trivial pressure conversions to the SparkFunBME280.cpp file and sure the references of SparkFunBME280.h accordingly.

### CODE REVIEW

**Comment by nseidle** [comment]
Thank you for the PR! This looks good but has a few issues (that may not be your fault)

1) This repo is the hardware repo so we can't accept PRs to the library. PRs should be issued on [the library](https://github.com/sparkfun/SparkFun_BME280_Arduino_Library).

2) This looks like a big change. I think you implemented some of the changes we already did on the main library so we'd need to sort those out. 

If you're open to it, please create a PR over on the library. Again, I really appreciate this PR we just can't bring it in via this hardware repo.

**Comment by nseidle** [comment]
@Pavel-Sayekat - I was able to load your code and test it. dewPointC() checks out but dewPointF() does not seem accurate (compared to online calcs). Where did you get these formulas? Also, dewpointFast failed (depends on F).

Your code has been added to v2.0.2 [over here](https://github.com/sparkfun/SparkFun_BME280_Arduino_Library/commit/6ef66682776b99937fabd89f8bbd8931daf68eed).

I think a simple C to F conversion will work for dewPointF() rather than running all the calculations a second time.

Please let me know if you have thoughts or if you want to open issues, please do so on the lib. Thanks for this PR!

**Comment by Pavel-Sayekat** [comment]
Sorry for repeating code and repeating it with flaw (a serious crime) and I copied the Dewpoint function from this link https://arduino.stackexchange.com/questions/33953/arduino-uno-wunderground-weather-station-ethernet-connection-failed.

**Comment by nseidle** [comment]
No worries! Thanks for letting us know. I'll add source comments on the next lib version.

**Pull request closed without merging**
